//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDemo.ModelsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        public int Id { get; set; }
        public string Cognome { get; set; }
        public string Nome { get; set; }
        public System.DateTime DataNascita { get; set; }
        public Nullable<int> IdCorso { get; set; }
    
        public virtual Corsi Corsi { get; set; }
    }
}
